apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-dep2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: nginx-port
      initContainers:
        - name: busybox
          image: busybox:latest
          command: ['sh', '-c', "until nslookup netology-svc.default.svc.cluster.local; do echo waiting for netology-svc; sleep 1; done"]