apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: netology-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: nginx-port
    name: nginx-port
  - protocol: TCP
    port: 9080
    targetPort: mtool-port
    name: mtool-port