kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-read
  namespace: default
subjects:
- kind: User
  name: reader
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-readonly
  apiGroup: rbac.authorization.k8s.io